version: '3.2'

volumes:
  streaming:
  database:
  fedora:
  solr:
  bundle:
  npms:

networks:
  external:
  internal:
    
services:
  db:
    image: avalonmediasystem/db:fedora4
    volumes:
      - database:/data
    environment:
      - AVALON_DB_PASSWORD
      - FEDORA_DB_PASSWORD
      - PGDATA=/data
      - POSTGRES_USER=postgres
    networks:
      internal:
  fedora:
    image: avalonmediasystem/fedora:4.7.5
    depends_on:
      - db
    volumes:
      - fedora:/data
    environment:
      - JAVA_OPTIONS=${JAVA_OPTIONS} -Dfcrepo.postgresql.password=${FEDORA_DB_PASSWORD} -Dfcrepo.postgresql.username=fedora -Dfcrepo.postgresql.host=db -Dfcrepo.modeshape.configuration=classpath:/config/jdbc-postgresql/repository.json
    networks:
      internal:
  solr:
    image: avalonmediasystem/solr:avalon-7.0
    volumes:
      - solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - avalon
      - /opt/solr/avalon_conf
    networks:
      internal:
  redis:
    image: redis:alpine
    networks:
      internal:
  avalon:
    image: avalonmediasystem/connect2018-workshop
    build:
      context: ./docker
    user: ${AVALON_UID}:${AVALON_GID}
    command: "/rails_init-dev.sh"
    depends_on:
      - db
      - fedora
      - solr
      - redis
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql://postgres@db/postgres         
      - FEDORA_URL=http://fedora:8080/fedora/rest
      - SOLR_URL=http://solr:8983/solr/avalon
      - SECRET_KEY_BASE=3fe397575565365108556c3e5549f139e8078a8ec8fd2675a83de96289b30550a266ac04488d7086322efbe573738e7b3ae005b2e3d9afd718aa337fa5e329cf
    volumes:
      - .:/home/app/avalon
      - bundle:/usr/local/bundle
      - npms:/home/app/node_modules
    ports:
      - 3000:3000 
    networks:
      external:
      internal:
    stdin_open: true
    tty: true
