development:
  url: <%= ENV["SOLR_URL"] || "http://127.0.0.1:#{ENV.fetch('SOLR_DEVELOPMENT_PORT', 8983)}/solr/hydra-development" %>
test:
  url: <%= ENV["SOLR_URL"] || "http://127.0.0.1:#{ENV.fetch('SOLR_DEVELOPMENT_PORT', 8985)}/solr/hydra-test" %>
production:
  url: <%= ENV["SOLR_URL"] || "http://your.production.server:8080/bl_solr/core0" %>
